# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_restaurant', models.ImageField(upload_to='logo')),
                ('restaurant_namme', models.CharField(max_length=100, verbose_name='Restaurant_namme')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('wage', models.CharField(max_length=9, verbose_name='Wage')),
                ('employer_mail', models.EmailField(max_length=254, verbose_name='Employer_mail')),
                ('position', models.CharField(max_length=36, verbose_name='Position')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('detail_job', models.TextField(verbose_name='Detail_job')),
                ('job_requirements', models.TextField(verbose_name='Job_requirements')),
                ('why_love_this_job', models.TextField(verbose_name='Why_love_this_job')),
            ],
        ),
    ]
