# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='wage',
            field=models.CharField(max_length=20, verbose_name='Wage'),
        ),
    ]
