# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_post_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='city',
            field=models.CharField(blank=True, choices=[('hn', 'Hà Nội'), ('sg', 'Tp.Hồ Chí Minh')], default='sg', max_length=50, null=True, verbose_name='City'),
        ),
    ]
