# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170702_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='detail_job',
        ),
        migrations.AddField(
            model_name='job',
            name='post',
            field=models.ManyToManyField(to='app.Post'),
        ),
    ]
