# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_myprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='contact_employer',
            field=models.CharField(max_length=30, null=True, verbose_name='Contact_employer'),
        ),
        migrations.AddField(
            model_name='post',
            name='deadline',
            field=models.CharField(max_length=20, null=True, verbose_name='Deadline'),
        ),
        migrations.AddField(
            model_name='post',
            name='job_description',
            field=models.TextField(null=True, verbose_name='Job_description'),
        ),
    ]
