# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20170706_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='gender',
            field=models.CharField(max_length=20, null=True, verbose_name='Gender'),
        ),
    ]
