# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20170706_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
