# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20170706_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='wage',
            field=models.CharField(max_length=100, verbose_name='Wage'),
        ),
    ]
