# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20170706_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contact_employer',
            field=models.CharField(max_length=100, null=True, verbose_name='Contact_employer'),
        ),
        migrations.AlterField(
            model_name='post',
            name='experience',
            field=models.CharField(max_length=100, null=True, verbose_name='Experience'),
        ),
        migrations.AlterField(
            model_name='post',
            name='gender',
            field=models.CharField(max_length=100, null=True, verbose_name='Gender'),
        ),
    ]
