# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20170706_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='post',
            name='address',
            field=models.CharField(max_length=256, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='post',
            name='contact_employer',
            field=models.CharField(max_length=256, null=True, verbose_name='Contact_employer'),
        ),
        migrations.AlterField(
            model_name='post',
            name='experience',
            field=models.CharField(max_length=256, null=True, verbose_name='Experience'),
        ),
        migrations.AlterField(
            model_name='post',
            name='gender',
            field=models.CharField(max_length=256, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='post',
            name='job_feature',
            field=models.CharField(max_length=256, null=True, verbose_name='Job_feature'),
        ),
        migrations.AlterField(
            model_name='post',
            name='restaurant_namme',
            field=models.CharField(max_length=256, verbose_name='Restaurant_namme'),
        ),
        migrations.AlterField(
            model_name='post',
            name='type_job',
            field=models.CharField(max_length=256, null=True, verbose_name='Type_job'),
        ),
        migrations.AlterField(
            model_name='post',
            name='wage',
            field=models.CharField(max_length=256, verbose_name='Wage'),
        ),
    ]
