# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20170706_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='logo_restaurant',
            field=models.CharField(max_length=256, verbose_name='Logo_restaurant'),
        ),
    ]
